# ----------------------------------------------
# --------
#
# Cluster and Cloud Computing Assignment 2 - Team 53
# 
# Authors: 
# - Chi Yin Wong (Student ID: 836872)
# - Kaiquan Lin (Student ID: 1147233)
# - Renkai Liao (Student ID: 1141584)
# - Renwei Hu (Student ID: 1067974)
# - Siwat Chairattanamanokorn (Student ID: 1338152)
#
# Author of this file:
# - Renwei Hu (Student ID: 1067974)
#
# Location:
# - Melbourne
#
# --------
# ----------------------------------------------

---
- name: Format volumes
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ volume }}"

- name: Mount volumes on nodes
  become: yes
  mount:
    path: "{{ mountpoint }}"
    src: "{{ volume }}"
    fstype: xfs
    state: mounted