---
# Basic set up for instances
# Install dependencies
- name: Update the existing list of packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['curl', 'git', 'python3-pip', 'python3-setuptools', 'vim', 'xfsprogs']
    state: latest
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Update pip
  become: yes
  ansible.builtin.pip:
    name: 'pip'
    state: latest

- name: Install openstacksdk
  become: yes
  ansible.builtin.pip:
    name: 'openstacksdk'
    state: latest