# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: Cloud
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: data-vol-1
    vol_size: 100
  - vol_name: data-vol-2
    vol_size: 100
  - vol_name: data-vol-3
    vol_size: 100
  - vol_name: data-vol-4
    vol_size: 100

# Security group
security_groups:
  - name: test_ssh
    description: "Test security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: test_http
    description: "Test security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: swarm
    description: "Security group for Docker Swarm"
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: data-vol-1
  - name: instance-2
    volumes: data-vol-2
  - name: instance-3
    volumes: data-vol-3


