# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: Cloud
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: data-vol-4
    vol_size: 100

# Security group
security_groups:
  - name: test_ssh
    description: "Test security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: test_http
    description: "Test security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couch1
    description: "Security group for Docker Swarm"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couch2
    description: "Security group for Docker Swarm"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couch3
    description: "Security group for Docker Swarm"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-4
    volumes: data-vol-4



