---
- name: Format volumes
  become: yes
  filesystem:
    fstype: xfs
    dev: "/dev/vdb"

# Initialise CouchDB in Docker
- name: Stop CouchDB container if exist
  become: yes
  docker_container:
    name: couchdb
    state: absent

- name: Start Docker container
  become: yes
  docker_container:
    name: "{{ couchdb_container}}"
    image: "{{ couchdb_image }}"
    state: started
    ports:
      - "4369:4369"
      - "5984:5984"
      - "9100:9100"
    env:
      NODENAME: "{{ ansible_host }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ couchdb_cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""



