# ----------------------------------------------
# --------
#
# Cluster and Cloud Computing Assignment 2 - Team 53
# 
# Authors: 
# - Chi Yin Wong (Student ID: 836872)
# - Kaiquan Lin (Student ID: 1147233)
# - Renkai Liao (Student ID: 1141584)
# - Renwei Hu (Student ID: 1067974)
# - Siwat Chairattanamanokorn (Student ID: 1338152)
#
# Author of this file:
# - Renwei Hu (Student ID: 1067974)
#
# Location:
# - Melbourne
#
# --------
# ----------------------------------------------

---
# Initialise CouchDB in Docker
- name: Stop CouchDB container if exist
  become: yes
  community.docker.docker_container:
    name: "{{ couchdb_container}}"
    state: absent

- name: Initialise Docker container
  become: yes
  community.docker.docker_container:
    name: "{{ couchdb_container}}"
    image: "{{ couchdb_image }}"
    state: started
    ports:
      - "4369:4369"
      - "5984:5984"
      - "9100:9100"
    env:
      NODENAME: "{{ ansible_host }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ couchdb_cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""
  when: inventory_hostname in groups['MRC_NODES'] and inventory_hostname not in groups['MRC_NODES'][3]


# Ensure not overwrite the CouchDB config files
- name: Copy CouchDB data to host
  become: yes
  ansible.builtin.command: "docker cp {{ couchdb_container }}:{{ couchdb_data_dir }} {{ host_data_volume }}"
  when: inventory_hostname in groups['MRC_NODES'] and inventory_hostname not in groups['MRC_NODES'][3]


- name: Stop CouchDB container again
  become: yes
  community.docker.docker_container:
    name: "{{ couchdb_container}}"
    state: stopped
  when: inventory_hostname in groups['MRC_NODES'] and inventory_hostname not in groups['MRC_NODES'][3]


- name: Run Docker container with volume mounted
  become: yes
  community.docker.docker_container:
    name: "{{ couchdb_container}}"
    image: "{{ couchdb_image }}"
    state: started
    ports:
      - "4369:4369"
      - "5984:5984"
      - "9100:9100"
    env:
      NODENAME: "{{ ansible_host }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ couchdb_cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""
    volumes:
      - "data:/opt/couchdb/data"
  when: inventory_hostname in groups['MRC_NODES'] and inventory_hostname not in groups['MRC_NODES'][3]




