---
- name: Create build directory
  become: yes
  file:
    path: /harvester
    state: directory

- name: Copy files
  become: yes
  copy:
    src: ../crawler/
    dest: /harvester

- name: Build harvester container image
  community.docker.docker_image:
    name: harvester
    build:
      path: /harvester
    source: build
    state: present

- name: Stop harvester container if exist
  become: yes
  community.docker.docker_container:
    name: harvester
    state: absent

- name: Launch harvester
  become: yes
  community.docker.docker_container:
    name: harvester
    image: harvester
    state: started
    ports:
      - "4369:4369"
      - "5984:5984"
      - "9100:9100"
    env:
      SCENARIO: Crime
      PYTHONUNBUFFERED: "1"