# ----------------------------------------------
# --------
#
# Cluster and Cloud Computing Assignment 2 - Team 53
# 
# Authors: 
# - Chi Yin Wong (Student ID: 836872)
# - Kaiquan Lin (Student ID: 1147233)
# - Renkai Liao (Student ID: 1141584)
# - Renwei Hu (Student ID: 1067974)
# - Siwat Chairattanamanokorn (Student ID: 1338152)
#
# Author of this file:
# - Renwei Hu (Student ID: 1067974)
#
# Location:
# - Melbourne
#
# --------
# ----------------------------------------------

---
# Set up CouchDB cluster
# Join together nodes
- name: Start cluster setup
  uri:
    url: http://{{ groups['MRC_NODES'][0] }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\": \"0.0.0.0\", \"username\":\"{{ couchdb_user }}\", \"password\": \"{{ couchdb_pass }}\", \"port\": \"5984\", \"remote_node\": \"{{ inventory_hostname }}\", \"node_count\": \"3\",\"remote_current_user\": \"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_pass }}\"}"
  when: inventory_hostname in groups['MRC_NODES'] and inventory_hostname not in groups['MRC_NODES'][0] and inventory_hostname not in groups['MRC_NODES'][3]

- name: Join other nodes
  uri:
    url: http://{{ groups['MRC_NODES'][0] }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\":\"add_node\",\"host\":\"{{ inventory_hostname }}\",\"port\":\"5984\",\"username\":\"{{ couchdb_user }}\",\"password\":\"{{ couchdb_pass }}\"}"
  when: inventory_hostname in groups['MRC_NODES'] and inventory_hostname not in groups['MRC_NODES'][0] and inventory_hostname not in groups['MRC_NODES'][3]

- name: Complete cluster setup
  uri:
    url: http://{{ groups['MRC_NODES'][0] }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    status_code: 200, 201
    body_format: json
    body: "{\"action\":\"finish_cluster\"}"
  run_once: true
  ignore_errors: True
