# ----------------------------------------------
# --------
#
# Cluster and Cloud Computing Assignment 2 - Team 53
# 
# Authors: 
# - Chi Yin Wong (Student ID: 836872)
# - Kaiquan Lin (Student ID: 1147233)
# - Renkai Liao (Student ID: 1141584)
# - Renwei Hu (Student ID: 1067974)
# - Siwat Chairattanamanokorn (Student ID: 1338152)
#
# Author of this file:
# - Renwei Hu (Student ID: 1067974)
#
# Location:
# - Melbourne
#
# --------
# ----------------------------------------------

- hosts: localhost
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true

  roles:
    - role: create-volume
    - role: create-security-group
    - role: create-instance

- hosts: MRC_NODES
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true
  become: yes

  roles:
  - role: common
  - role: mount-volumes
  - role: install-docker
  - role: init-couchdb
  - role: set-couchdb-cluster
  - role: deploy-harvester
  - role: deploy-frontend