- hosts: localhost
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true

  roles:
    - role: create-volume
    - role: create-security-group
    - role: create-instance

- hosts: MRC_NODES
  vars_files:
    - host_vars/vars.yaml
  gather_facts: true
  become: yes

  roles:
  - role: common
  - role: mount-volumes
  - role: install-docker
  - role: init-couchdb
  - role: set-couchdb-cluster
  - role: deploy-harvester
  - role: deploy-frontend